[font]
size = 16.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

# You need install fonts first
# sudo pacman -S yay
# yay -S nerd-fonts-jetbrains-mono

[window]
opacity = 0.7
